name: SecureStack All-In-One Action Workflow - Optus demo
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for running secrets analysis within workflow
        id: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          
      - name: SecureStack - Secrets Analysis Step
        id: secrets
        uses: SecureStackCo/actions-secrets@v0.1.3
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
          flags: '-d 1 --info'
          
      - name: SecureStack - Software Composition Analysis Step
        id: code
        uses: SecureStackCo/actions-code@v0.1.1
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
          language: node
          flags: '--info'
          
      - name: SecureStack - Web Exposure Analysis Step
        id: exposure
        uses: SecureStackCo/actions-exposure@v0.1.3
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
          flags: '--dom -r --info'
          
      - name: SecureStack - Software Bill of Materials
        id: sbom
        uses: SecureStackCo/actions-sbom@v0.1.1
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
          
      - name: Generate CycloneDX SBOM
        id: cyclonedx-sbom
        uses: CycloneDX/gh-node-module-generatebom@master
        with: 
          output: './app.niftybank.org.cyclonedx.bom.xml'
          path: './'
          
