name: SecureStack Secrets Scan Action
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for running secrets analysis within workflow
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'
      - name: Run script file
        run: |
          ls -al
        shell: bash
      - name: Secrets Analysis Step
        id: secrets
        uses: SecureStackCo/actions-secrets@v0.1.0
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY_SECRET }}
          securestack_app_id: ad60440c-8215-478e-a553-8c1d172bf8e8
          severity: critical
          flags: '-d 1 -a ad60440c-8215-478e-a553-8c1d172bf8e8'
